### ISSUE TITLE
你好，我的项目有出现这个bug,但是将你这个放进去之后，我有些按钮点击不了了。

### ISSUE THREAD

**Issue by Stevezhong0506** [zhaokunhaoa/SafeTransition#1]

**Comment by kevin-geng** [comment]
@simplecode-k 作者解答一下吧，我也遇到了这个bug“Can't add self as subview”。

**Comment by zhaokunhaoa** [comment]
不好意思，刚看到，你的情况因为没有代码，不好判断，把我的文件移除项目，按钮就可以点么？我暂时想不到这个分类对按钮的影响 @Stevezhong0506
