### ISSUE TITLE
相册的vc在push的时候会有问题吗？

### ISSUE THREAD

**Issue by zer0err** [zhaokunhaoa/SafeTransition#2]
为解决我司项目中的add self as subview的bug，引用了你的这个文件。
我大概看过，没什么大问题，在引过项目之后个人也没有发现任何问题。
我想知道你在用了这个文件之后有没有遇到过什么别的bug。

谢谢〜

**Comment by zhaokunhaoa** [comment]
哈哈, 我当时做出来, 我leader也一样.毕竟runtime hook了系统所有的push和pop, 自己也没有百分百的保证, 所幸几百万用户验证过后, 并无问题, 且解决了这个bug. 最初我限制只有iOS7才生效, 后来统计到iOS8 和 iOS9也有, 于是打开了限制, 全部系统版本生效了

**Comment by ericoda** [comment]
好想加到项目里面去啊。。。唉。。。可惜不是我能控制。。。thanks anyway
